### ISSUE TITLE
possible bug in edge term function

### ISSUE THREAD

**Issue by williamdemeo** [UACalc/uacalcsrc#3]
Below is the operation table of a commutative idempotent binar that Cliff and I are looking at.  (It should be tractable and we want to know why.)

0 2 1 1
2 1 0 2
1 0 2 0
1 2 0 3

If we select "Edge term some k" from the "Idempotent Algs" menu, the following appears in the computations window:

  "Looking for a cube term blocker  using A. Kazda's new polynomial time algorithm.
  There is no cube term blocker so A does have an edge term.  (0 ms)"

This is false, since there is, in fact, a cube term blocker---namely the pair (D, S), where D = {0, 1, 2} and S = {0, 1, 2, 3}.  

Moreover, as Cliff pointed out, this algebra has a semilattice quotient, so it can't have an edge term.

**Comment by williamdemeo** [comment]
Below is the output of cubeTermBlockerIdempotent when run on the algebra in the file CIB4-no-edge-term.ua (which now resides in the [UACalc/AlgebraFiles/Bergman](https://github.com/UACalc/AlgebraFiles/tree/master/Bergman) directory).

I believe a cube term blocker for this algebra would be the pair of subuniverses (C, D), where 

C: [0, 1, 2], D: [0, 1, 2, 3]

From the output below, it seems the currently implemented algorithm only considers the case where C (the smaller subuniverse of the cube term blocker) has one element.

c: 0, e: 1
ce2: [0, 1, 2]
c: 0, e: 2
ce2: [0, 1, 2]
c: 0, e: 3
ce2: [0, 1, 2, 3]
C: [0], D: [0, 1, 2]
arity: 2, j: 0, k: 1, arr: [0], D.universeSize: 3
arity: 2, j: 0, k: 1, arr: [1], D.universeSize: 3
C: [0], D: [0, 1, 2]
c: 1, e: 0
ce2: [0, 1, 2]
c: 1, e: 2
ce2: [0, 1, 2]
c: 1, e: 3
ce2: [0, 1, 2, 3]
C: [1], D: [0, 1, 2]
arity: 2, j: 0, k: 1, arr: [0], D.universeSize: 3
C: [1], D: [0, 1, 2]
c: 2, e: 0
ce2: [0, 1, 2]
c: 2, e: 1
ce2: [0, 1, 2]
c: 2, e: 3
ce2: [0, 1, 2, 3]
C: [2], D: [0, 1, 2]
arity: 2, j: 0, k: 1, arr: [0], D.universeSize: 3
C: [2], D: [0, 1, 2]
c: 3, e: 0
ce2: [0, 1, 2, 3]
c: 3, e: 1
ce2: [0, 1, 2, 3]
c: 3, e: 2
ce2: [0, 1, 2, 3]
C: [3], D: [0, 1, 2, 3]
arity: 2, j: 0, k: 1, arr: [0], D.universeSize: 4
C: [3], D: [0, 1, 2, 3]
CIB4-no-edge-term has cube term blocker: null

**Comment by ralphfreese** [comment]
It should be fixed. Is there a way to close this issue? Your the owner so maybe you can do it. Or maybe the assignee (which is no one?) has to do it. Anyway I like this system for reporting bugs and other issues.

**Comment by ralphfreese** [comment]
I now see a close issue so I'll try that.
